### ISSUE TITLE
The "Share your market" link does not contain the "referrer"

### ISSUE THREAD

**Issue by omarkohl** [manifoldmarkets/manifold#1161]
At the bottom of my market there is a box that says "Share your market! Earn a M$250 referral bonus if a new user signs up using the link.". The link that I get when clicking on "Copy link" does not contain the "referrer=USERNAME".

**Comment by jahooma** [comment]
Hi Omar,

Yes, that's true and it's a bit confusing.

But if no referrer is specified, it by default gives the referral bonus to the creator of the market.

Maybe we should add it anyway so market creators have more confidence they will get the bonus?

Cheers,
James

**Comment by omarkohl** [comment]
>Maybe we should add it anyway so market creators have more confidence they will get the bonus?

Good idea! Quoting the Zen of Python "Explicit is better than implicit" :-)

**Comment by omarkohl** [comment]
> But if no referrer is specified, it by default gives the referral bonus to the creator of the market.

It's a little out of scope for this issue, but I will also say that I find this to be very surprising.

It's frequently considered good form to state that you are getting a benefit out of something e.g. when I post a link to my market I would say "Full disclosure: I will get a bonus if you sign up after using the link". Having this happen in the background gives me no way of opting out and in fact I did not even know about this. I suspect the same is true for many (most?) other users.

I'll concede that this is a very minor _problem_ :man_shrugging:.
