### ISSUE TITLE
[Bug] Embarrassing newline problem in descriptions and comments

### ISSUE THREAD

**Issue by dreeves** [manifoldmarkets/manifold#1273]
## Replicata

1. Go to any market and start typing a comment
2. Maybe it looks like this:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/9928/204915356-9390aa08-c1ae-444b-89f3-4d51137c5e59.png">

3. Now hit submit to post your comment

## Expectata

That the posted version has actual paragraph breaks.

## Resultata

I see something like this:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/9928/204915621-393f9751-7e01-4500-9c7c-de4ba21be424.png">

https://manifold.markets/MichaelWheatley/weighted-poll-will-biden-be-preside#kmn3VxN5w3lisa8JWIbU

This is actually pretty embarrassing. I look like a crazy person responding with an impenetrable wall of text!

**Comment by dreeves** [comment]
Yev adds:
The bug was only introduced a few days ago
When we moved tiptap rendering to the server
It also broke mentions, twitter embeds, and market grids

**Comment by dreeves** [comment]
And fixed! Thank you so much!

(It occurs to me to clarify, the embarrassingness was for me, the user, because it looked like I didn't understand the concept of paragraphs. Didn't mean to shame y'all into rushing a fix by calling it embarrassing to have been buggy like that!)

**Comment by sipec** [comment]
fixed by #1275 (erm #1282 actually)
