### ISSUE TITLE
Server-side rendering of all pages involving authentication is busted

### ISSUE THREAD

**Issue by mqp** [manifoldmarkets/manifold#138]
When you load any page that has a "logged in" and "logged out" version, the server-side rendering will always produce the logged-out version, because it has no idea whether you are logged in or out. This produces extremely janky looking UI and hurts performance. The most glaring offender is simply the home page.

There would be two reasonable-sounding approaches to fix this:

1. Turn off server-side rendering for pages with dynamic content (basically every page.)

This kind of concerns me because it seems like it's clearly not the Next.js happy path. They don't just have a config that says "don't do it anymore." We would have to reorganize a bunch of stuff, like [this guy](https://dev.to/apkoponen/how-to-disable-server-side-rendering-ssr-in-next-js-1563).

2. Actually get the correct information on the server so that it can render a correct page.

This seems like it shouldn't be very hard. Next.js provides a `getServerSideProps` API where you can populate e.g. user data during SSR. The trick is getting the user data there in the first place. [This package](https://github.com/gladly-team/next-firebase-auth) does it, but it's not clear to me if we want to adopt it wholesale. Obviously we would need to use cookies instead of local storage for the session information, but that's fine.

(Note: There's also a phenomenon where, as a kind of performance optimization, we cache the user info that we saw on last page load in local storage, and use it optimistically next time you load the app, for the first "logged in" view you see. This is weird because there's a very visible lag and you can see your balance suddenly change because of this basically every time you open Manifold. If we did this step number 2, we would basically be undoing that performance optimization, so we would also eliminate this jankiness.)

**Comment by jahooma** [comment]
Great, thanks for looking into this! 

We use `getStaticProps` heavily (https://nextjs.org/docs/basic-features/data-fetching/get-static-props), which is not really a form a server-side rendering. It simply caches a static page which is served to everyone. It's much faster than trying to authenticate the user on the server, and it is recommended in their docs.

We should try to improve places where the experience is bad. That includes the '/' redirecting to '/home' case which you highlighted. Maybe we could convert that one page to be server-side rendered? But even that seems slow (because SSR is slow).

I think we'd prefer to merge '/' and '/home' back into a single route, and choose how to render the page completely client-side. (https://manifoldmarkets.notion.site/merge-and-home-again-d81b312d107b46b1a8630caf951bd6e3)

What do you think?

**Comment by mqp** [comment]
> We use getStaticProps heavily (https://nextjs.org/docs/basic-features/data-fetching/get-static-props), which is not really a form a server-side rendering. It simply caches a static page which is served to everyone. It's much faster than trying to authenticate the user on the server, and it is recommended in their docs.

Yeah, the Next.js documentation calls this "static site generation", in contrast to "server-side rendering", which it just does for every page in `/pages` by default. Our whole site is currently being "server-side rendered", in that the server will run JS and generate HTML for every page load, it's just that for some pages we render something wrong (e.g. `/`), and for other pages we render very little (e.g. the markets page -- we just render it with no markets.)

> We should try to improve places where the experience is bad. That includes the '/' redirecting to '/home' case which you highlighted. Maybe we could convert that one page to be server-side rendered? But even that seems slow (because SSR is slow).

SSR shouldn't be slow. Suppose we don't try to server-side render the homepage feed, and just stick to the user info, so we know to render a correct sidebar, a "create market" thing on the top, and a loading indicator for the feed. The conceptual differences in what's happening here are:

- Instead of returning some HTML immediately, the server will be talking to Firebase to get user info before returning HTML.
- But then the client won't have to talk to Firebase to get that same user info.
- Instead of React rendering a whole mostly incorrect page and then re-rendering a correct page on top of it later, it will only render the correct page, saving work.

So "time to a correct page" should probably be lower. The main question might be: how much did we value getting an incorrect page visible on the client, sooner? In the case of the whole "main part is wrong" thing, we valued it negatively. But in the case of "the cached user info showing up", it's arguable.

Here is where in a normal web app I would be like "OK, so just store a shared user info cache in memory on the server, and keep it up to date, so you can get the correct info basically instantly." But I don't know how to do that with Vercel.

> I think we'd prefer to merge '/' and '/home' back into a single route, and choose how to render the page completely client-side. (https://manifoldmarkets.notion.site/merge-and-home-again-d81b312d107b46b1a8630caf951bd6e3)

I think this is a reasonable thing to do if we don't want to start doing more stuff on the server as above.
