### ISSUE TITLE
No right/left page margin visible on small widths

### ISSUE THREAD

**Issue by mqp** [manifoldmarkets/manifold#140]
On smaller widths, the left/right margin on the page disappears. On some pages this is maybe OK (e.g. pages like the homepage feed, where there is just one big vertical column) but it looks particularly odd on pages with multiple-column layouts, like the explore feed when it's still in two-column mode. (The input at the top looks weird to have zero margin too.)

I would suggest fixing all pages to always have a small left/right margin at all widths.

![image](https://user-images.githubusercontent.com/428637/167032575-e272942a-4fd8-4fc5-9568-0d0df3f0a50f.png)

**Comment by sipec** [comment]
no longer the case
