### ISSUE TITLE
Sidebar gets all crunched up at medium widths

### ISSUE THREAD

**Issue by mqp** [manifoldmarkets/manifold#141]
At medium widths, before the sidebar is replaced with the bottom bar, there can be some ugly visual problems with it. The logo is not centered, my name is cut off, and the hamburger menu contents are all jammed against the left edge.

![image](https://user-images.githubusercontent.com/428637/167033019-37f53b78-c1fc-4939-a7fb-cfecfb6e15f9.png)

**Comment by sipec** [comment]
Fixed: 82199292
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18368938/174165907-fac116e0-6f0c-404e-87c7-205a95282f13.png">
