### ISSUE TITLE
If users name themselves after a static path their profile is inaccessible

### ISSUE THREAD

**Issue by mqp** [manifoldmarkets/manifold#142]
For example, I don't recommend naming yourself "markets". I mentioned this on Discord and I'm putting it here for posterity because we should really fix this and not forget it.

As discussed, I favor the fix "put user profiles under a separate URL path."

**Comment by dreeves** [comment]
Collecting my arguments for keeping usernames in the top-level namespace below. In which case this bug would be addressed by disallowing any static routes in the username validation function.

Things the username validation function should do:

1. Disallowing anything that matches an existing route
2. No 1- or 2-character usernames (Beeminder used to allow these and kinda regretted it)
3. Must not match a monster regex with things you think to reserve (happy to share what Beeminder uses)

And 3 isn't critical. Between single characters, things that are already static URLs, and things that are still available despite users filling the top-level namespace as fast as they can, you're not actually backing yourself into any kind of corner by not putting users in a folder, so to speak. It works for Facebook and Twitter and others.

Aesthetically, I think it's really nice to have manifold.markets/[name] URLs. If I want to point people to my stuff I like being able to say like facebook.com/dreev or bmndr.co/d or manifold.markets/dreev.

Also, when I link to manifold.markets/dreev/will-elon-buy-twitter or whatever, it's nice to be able to lop off the "/will-elon-buy-twitter" to see my other markets.

### Aren't markets, not users, the most fundamental thing on Manifold?

Yeah, it's similar to goals being the fundamental thing on Beeminder. In that case it makes sense to prefix the goal with whose goal it is. So my pushups goal is bmndr.co/d/push. I could see an argument for the creator being less fundamental on Manifold so it's slightly nicer to have manifold.markets/will-elon-musk-buy-twitter than manifold.markets/joeschmoe/will-elon-musk-buy-twitter.

### Is it a big pain to restrict usernames so there aren't collisions?

I don't think so. Mostly you can just let usernames take precedence. And you want restrictions on usernames anyway so whether they're top-level doesn't change much. Like, "home" is a slightly dumber username when it's manifold.markets/home vs manifold.markets/users/home but kinda dumb regardless. And it's not like users will ever fill up the namespace. If someday you want like manifold.markets/trades and some user took "trades" it won't be hard to find something that's not taken.

### Final thoughts

I'm extra weird but ideally I'd make users hand-pick the slug. Like you pick the title/question -- "Will Elon buy Twitter?" -- and then the UI says "now pick a one or two word slug for a nice url like "manifold.markets/dreev/twittermusk".

(You might actually need something like that for betting via Discord bots.)

**Comment by sipec** [comment]
We'd need to support old urls anyways to prevent link rot in markets we or others have already shared. Like:

/[x]/slug -> redirect to /mkt/slug
/[x] -> check if x is a valid user -> redirect to /user/x

**Comment by sipec** [comment]
resolved in #1766 by MayMeta 🙏
