### ISSUE TITLE
dislike markets

### ISSUE THREAD

**Issue by PatMyron** [manifoldmarkets/manifold#1499]
especially if likes are ever used as a market quality signal:
https://manifold.markets/IsaacKing/will-this-market-have-at-least-50-l

**Comment by bfinan** [comment]
an emphatic +1

**Comment by PatMyron** [comment]
https://github.com/manifoldmarkets/manifold/commit/2fb408321bb60ea8b88ba2e0ab6c720c068f250f

**Comment by bfinan** [comment]
nice work team
