### ISSUE TITLE
deduplicate orders

### ISSUE THREAD

**Issue by PatMyron** [manifoldmarkets/manifold#1508]
possible to spam limit orders by splitting limit orders like @franklinbaldo :)

<img width="83" alt="Screen Shot 2023-02-10 at 10 30 52 PM" src="https://user-images.githubusercontent.com/7014355/218236897-7304d79f-16aa-4f00-ab70-b83bc31069b8.png">

although currently split limit orders apparently behave differently? don't think they should

**Comment by PatMyron** [comment]
tbh it'd be nice to squash consecutive market orders by the same person too

**Comment by PatMyron** [comment]
> Server-side order deduplication can create issues with trading bots, as they would lose track of trades.

client-side deduplication would be sufficient. Mostly just concerned about the website UI being overwhelming due to the number of orders on some markets

**Comment by sipec** [comment]
ok i just made it a collated order book. check it out
