### ISSUE TITLE
Closed Form Solution for calculateCpmmAmountToProb

### ISSUE THREAD

**Issue by Wamba-Ivanhoe** [manifoldmarkets/manifold#1553]
Closed form solution for calculateCpmmAmountToProb

I believe this would be the implementation
```
export function calculateCpmmAmountToProb(
  state: CpmmState,
  prob: number,
  outcome: 'YES' | 'NO'
) {
  if (prob <= 0 || prob >= 1 || isNaN(prob)) return Infinity
  if (outcome === 'NO') prob = 1 - prob
  const { pool, p } = state
  const { YES: y, NO: n } = pool
  const k = y ** p * n ** (1 - p)
  return outcome === 'YES'
    ? // https://www.wolframalpha.com/input?i=-1+%2B+t+-+((-1+%2B+p)+t+(k%2F(n+%2B+b))^(1%2Fp))%2Fp+solve+b
      ((p * (prob - 1)) / ((p - 1) * prob)) ** (-p)*(k - n * ((p * (prob - 1)) / ((p - 1) * prob)) ** p)
    : (((1 - p) * (prob - 1)) / ((-p) * prob)) ** (p-1)*(k - y * (((1 - p) * (prob - 1)) / ((-p) * prob)) ** (1 - p))
}
```
For reference:
https://github.com/manifoldmarkets/manifold/blob/9c9f0a90b40d94393178bb6a7191f49946904ef5/common/src/calculate-cpmm.ts#L118-L143

**Comment by jahooma** [comment]
Whoa, this is amazing! If it works, it also makes the new multiple choice mechanism I had in mind much easier (it uses one binary cpmm per answer).

**Comment by Wamba-Ivanhoe** [comment]
Note:  The closed form solution is not bound to positive results, returning both positive and negative values in Mana.  For example if the market was at 97% and the target was 67% it would return a negative bet for the YES outcome, which would represent that you need to sell that much Mana worth of YES shares to move the market to 67%.

**Comment by Zentrik** [comment]
This looks right to me, I've checked my implementation fairly extensively https://github.com/Zentrik/ManifoldMarkets.jl/blob/master/src/helper.jl#L116 and it seems to match this one.

**Comment by Wamba-Ivanhoe** [comment]
Thanks Zentrik.   I am just a math & code hobbyist but I am not familiar with trying to publish on Github so I am not going to try to push it into the codebase myself.  I don't know how much of an optimization the closed form is over recursive binary search, but my hopes are that if it offers a worthwhile performance improvement that the closed form eventually makes it into the production code.

**Comment by Wamba-Ivanhoe** [comment]
Closed form in production
https://github.com/manifoldmarkets/manifold/commit/d2e18d04ffab144b3f72519a17817a3eb4b4b318
