### ISSUE TITLE
When navigating from someone else's profile to your own - the market list is not properly updated

### ISSUE THREAD

**Issue by Stvad** [manifoldmarkets/manifold#158]
![manifold-navigation-bug](https://user-images.githubusercontent.com/81347/167474764-5fb44141-f779-4a80-848b-6ae847fe345a.gif)

**Comment by jahooma** [comment]
I can reproduce. Thanks for reporting!

**Comment by jahooma** [comment]
Just pushed a fix! Should be live in ~2 min

**Comment by jahooma** [comment]
Closing as it's fixed.

**Comment by Stvad** [comment]
thanks!
