### ISSUE TITLE
Question title data vertically misaligned

### ISSUE THREAD

**Issue by mqp** [manifoldmarkets/manifold#164]
On the question cards that appear on the frontpage feed, the top of the card looks like this:

![image](https://user-images.githubusercontent.com/428637/167508080-6278e703-1d23-4307-8ef5-3b7867c3b161.png)

It would definitely look nicer if the bet data on the right was vertically aligned with the question asker on the left, instead of being randomly kind of almost-aligned.

(Sorry James!)

**Comment by mqp** [comment]
I can see that there's kind of a tradeoff between having this aligned and having it look like there's "too much white space" at the top right...hmm.

**Comment by sipec** [comment]
closing because old feed is dead
