### ISSUE TITLE
Cannot sign in with Apple on website

### ISSUE THREAD

**Issue by alfonsoSR** [manifoldmarkets/manifold#1946]
**Describe your problem**

The iOS version of the Manifold app allows you to sign up with Apple or Google. The Manifold website (manifold.markets) only lets you sing up/in with Google.

I created my account using "Sign up with Apple" in the app and cannot log in from my computer.

**OS and versions**
- OS: iOS 16.5.1
- Manifold app: 1.0.17
- Web browser: Safari 16.5.2 / DuckDuckGo 7.81.0

**Comment by sipec** [comment]
does https://manifold.markets/login introduced in #2533 fix this for you?

**Comment by eppsilon** [comment]
This isn't working for me in Safari 17.5 or Arc 1.47.1 (Chromium 126). Clicking the button opens a pop-up window, but the window closes automatically and nothing else happens. I see this in the console:
<img width="409" alt="image" src="https://github.com/manifoldmarkets/manifold/assets/5643/89d65f22-4bdf-4b87-9daf-08494d6fef3c">
