### ISSUE TITLE
Privacy policy and Terms of service are absent

### ISSUE THREAD

**Issue by maksugr** [manifoldmarkets/manifold#1976]
Hi folks,
[Terms of service](https://manifold.markets/terms) and [Privacy policy](https://manifold.markets/privacy) buttons on the bottom of the [About page](https://manifold.markets/about) lead to 404.

**Comment by maksugr** [comment]
@alat-rights Please, try to click on these links at the bottom of the About page. Everything is okay with SSR, but there is a problem with CSR.

https://github.com/manifoldmarkets/manifold/assets/8699120/64eb44af-7b5d-447f-bfd5-0718e0ff4914

**Comment by alat-rights** [comment]
Oops, you're right.
