### ISSUE TITLE
Twitch control dock is not displaying available groups; cannot feature markets

### ISSUE THREAD

**Issue by nleseul** [manifoldmarkets/manifold#1999]
The Twitch control dock page is currently showing an empty dropdown for selecting groups. Since you cannot browse markets from the control dock without first selecting groups, there is no way to browse markets. Since, as far as I know, there is no way to feature a market in the Twitch widget except through the control dock, this means that the Twitch widget cannot currently be used.

Looking at the JS console, it looks like the [/v0/groups](https://manifold.markets/api/v0/groups) API endpoint the control dock uses is currently generating HTTP 500 errors, which are not being gracefully handled by the page.

**Comment by sipec** [comment]
sorry, we're kinda silently abandoned the twitch integration for a while now. I don't think it's likely for us to fix issues with it.

`/v0/groups` endpoint was added back though so perhaps that fixes this particular issue
