### ISSUE TITLE
Notifications do not load

### ISSUE THREAD

**Issue by travis-mark** [manifoldmarkets/manifold#2044]
URL:

https://manifold.markets/notifications

Returned via browser:

Application error: a client-side exception has occurred (see the browser console for more information).

Console Dump: 

[Error] Fetch API cannot load https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?gsessionid=oFdhy8RnjpUb94ZzGuzYDdIv9HISL1sNbkv-AqQxg4k&VER=8&database=projects%2Fmantic-markets%2Fdatabases%2F(default)&RID=rpc&SID=i-12C1xmiPTRSie2igFKBA&CI=0&AID=22&TYPE=xmlhttp&zx=8h4dva5e9kxt&t=1 due to access control checks.
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:26363)
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:37781)
	te (_app-c6b16a7525760e1b.js:1251:14521)
	nd (_app-c6b16a7525760e1b.js:1251:32956)
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:39613)
	eC (_app-c6b16a7525760e1b.js:1251:10017)

[Error] Fetch API cannot load https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?gsessionid=oFdhy8RnjpUb94ZzGuzYDdIv9HISL1sNbkv-AqQxg4k&VER=8&database=projects%2Fmantic-markets%2Fdatabases%2F(default)&RID=rpc&SID=i-12C1xmiPTRSie2igFKBA&CI=0&AID=22&TYPE=xmlhttp&zx=8zb77msl41pd&t=2 due to access control checks.
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:26363)
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:37781)
	te (_app-c6b16a7525760e1b.js:1251:14521)
	nd (_app-c6b16a7525760e1b.js:1251:32956)
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:39613)
	(anonymous function)
	(anonymous function) (_app-c6b16a7525760e1b.js:1251:12996)

[Info] Build: production / update news / https://github.com/manifoldmarkets/manifold/commit/f7dd5db91ab72dd0c41f3ca6992e774d0f1feb06 (_app-c6b16a7525760e1b.js, line 186)

[Error] TypeError: undefined is not an object (evaluating 'x[0].data.answerText') — income-summary-notifications.tsx:97
	a5 (framework-0e91cc6ba5b64b05.js:9:69822)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:70334)
	lH (framework-0e91cc6ba5b64b05.js:9:51356)
	uY (framework-0e91cc6ba5b64b05.js:9:90793)
	e (framework-0e91cc6ba5b64b05.js:9:111127)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:111136)
	oI (framework-0e91cc6ba5b64b05.js:9:111648)
	oS (framework-0e91cc6ba5b64b05.js:9:95020)
	oS
	x (framework-0e91cc6ba5b64b05.js:33:1375)
	T (framework-0e91cc6ba5b64b05.js:33:1905)

[Error] TypeError: undefined is not an object (evaluating 'x[0].data.answerText') — income-summary-notifications.tsx:97
	$ (main-4932ba273b7526d5.js:1:8635)
	fn (main-4932ba273b7526d5.js:1:7703)
	componentDidCatch (main-4932ba273b7526d5.js:1:6264)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:70442)
	lH (framework-0e91cc6ba5b64b05.js:9:51356)
	uY (framework-0e91cc6ba5b64b05.js:9:90793)
	e (framework-0e91cc6ba5b64b05.js:9:111127)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:111136)
	oI (framework-0e91cc6ba5b64b05.js:9:111648)
	oS (framework-0e91cc6ba5b64b05.js:9:95020)
	oS
	x (framework-0e91cc6ba5b64b05.js:33:1375)
	T (framework-0e91cc6ba5b64b05.js:33:1905)

[Error] A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
	$ (main-4932ba273b7526d5.js:1:8652)
	fn (main-4932ba273b7526d5.js:1:7703)
	componentDidCatch (main-4932ba273b7526d5.js:1:6264)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:70442)
	lH (framework-0e91cc6ba5b64b05.js:9:51356)
	uY (framework-0e91cc6ba5b64b05.js:9:90793)
	e (framework-0e91cc6ba5b64b05.js:9:111127)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:111136)
	oI (framework-0e91cc6ba5b64b05.js:9:111648)
	oS (framework-0e91cc6ba5b64b05.js:9:95020)
	oS
	x (framework-0e91cc6ba5b64b05.js:33:1375)
	T (framework-0e91cc6ba5b64b05.js:33:1905)

[Error] TypeError: undefined is not an object (evaluating 'x[0].data.answerText') — income-summary-notifications.tsx:97
	a5 (framework-0e91cc6ba5b64b05.js:9:69822)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:70334)
	lH (framework-0e91cc6ba5b64b05.js:9:51356)
	uY (framework-0e91cc6ba5b64b05.js:9:90793)
	e (framework-0e91cc6ba5b64b05.js:9:111127)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:111136)
	oI (framework-0e91cc6ba5b64b05.js:9:111648)
	oS (framework-0e91cc6ba5b64b05.js:9:95020)
	oS
	x (framework-0e91cc6ba5b64b05.js:33:1375)
	T (framework-0e91cc6ba5b64b05.js:33:1905)

[Error] TypeError: undefined is not an object (evaluating 'x[0].data.answerText') — income-summary-notifications.tsx:97
	$ (main-4932ba273b7526d5.js:1:8635)
	fn (main-4932ba273b7526d5.js:1:7703)
	componentDidCatch (main-4932ba273b7526d5.js:1:6264)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:70442)
	lH (framework-0e91cc6ba5b64b05.js:9:51356)
	uY (framework-0e91cc6ba5b64b05.js:9:90793)
	e (framework-0e91cc6ba5b64b05.js:9:111127)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:111136)
	oI (framework-0e91cc6ba5b64b05.js:9:111648)
	oS (framework-0e91cc6ba5b64b05.js:9:95020)
	oS
	x (framework-0e91cc6ba5b64b05.js:33:1375)
	T (framework-0e91cc6ba5b64b05.js:33:1905)

[Error] A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
	$ (main-4932ba273b7526d5.js:1:8652)
	fn (main-4932ba273b7526d5.js:1:7703)
	componentDidCatch (main-4932ba273b7526d5.js:1:6264)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:70442)
	lH (framework-0e91cc6ba5b64b05.js:9:51356)
	uY (framework-0e91cc6ba5b64b05.js:9:90793)
	e (framework-0e91cc6ba5b64b05.js:9:111127)
	(anonymous function) (framework-0e91cc6ba5b64b05.js:9:111136)
	oI (framework-0e91cc6ba5b64b05.js:9:111648)
	oS (framework-0e91cc6ba5b64b05.js:9:95020)
	oS
	x (framework-0e91cc6ba5b64b05.js:33:1375)
	T (framework-0e91cc6ba5b64b05.js:33:1905)

[Error] Failed to load resource: the server responded with a status of 502 () (shim.js.map, line 0)

[Error] Error rendering page:  – Error: Cancel rendering route — index.js:432
Error: Cancel rendering route — index.js:432c — index.js:432(anonymous function) — index.js:423Promiseea — index.js:421
	error

[Info] Build: production / update news / https://github.com/manifoldmarkets/manifold/commit/f7dd5db91ab72dd0c41f3ca6992e774d0f1feb06 (_app-c6b16a7525760e1b.js, line 186)

**Comment by jahooma** [comment]
Can you try again? I think I fixed this!

**Comment by travis-mark** [comment]
Looks like it's working, thanks! Closing issue.
