### ISSUE TITLE
"Sign up" page crashes Brave browser

### ISSUE THREAD

**Issue by YairRand** [manifoldmarkets/manifold#2195]
Clicking "Sign up" on the website crashes the browser, when using the Brave browser on Ubuntu. The issue does not appear on Windows 10. I haven't checked other operating systems.

**Comment by sipec** [comment]
huh. I wonder if all chromium on ubuntu is busted. I don't think anyone in the office has a way of testing this easily

**Comment by YairRand** [comment]
Tested on Chromium itself on Ubuntu, seems to be fine there.
