### ISSUE TITLE
Value for argument "data" is not a valid Firestore document. Input object is deeper than 20 levels or contains a cycle

### ISSUE THREAD

**Issue by jettjaniak** [manifoldmarkets/manifold#2247]
Can't create a private question. That would be my first one. Adding a public one w/o description worked

https://manifold.markets/JettJaniak

<img width="892" alt="image" src="https://github.com/manifoldmarkets/manifold/assets/17082351/60dfe834-3008-434f-b63f-49a153f844b9">

**description**: 2.5k characters, nested bullet points 

<img width="890" alt="image" src="https://github.com/manifoldmarkets/manifold/assets/17082351/d047a779-37f3-4999-88e1-932e8d384811">

An unknown error occurred: Error: Value for argument "data" is not a valid Firestore document. Input object is deeper than 20 levels or contains a cycle. at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:258:15) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:271:13) at validateUserInput (/usr/src/app/node_modules/@google-cloud/firestore/build/src/serializer.js:265:13)

**Comment by jettjaniak** [comment]
I can't update insert the long description into existing question or comment with it either

**Comment by jettjaniak** [comment]
Actually some short parts of this description (8-10 bullet points) won't submit as comments "error submitting comment, try again?" I can share the full desc with someone if that's helpful

**Comment by jettjaniak** [comment]
removing all bullet points and hyperlinks works

**Comment by sipec** [comment]
thanks for looking into this. 
fortunately we now store markets in postgres which does not have a depth limit to its json data so this should no longer be an issue
