### ISSUE TITLE
Twitter cards don't render the og:image

### ISSUE THREAD

**Issue by quantizor** [manifoldmarkets/manifold#2301]
I think it's because the current meta tag setup is providing webp images. png would be more compatible; it looks like simply subbing `.webp` in the URL with `.png` should do it.

**Comment by sipec** [comment]
can't repro. this is what it shows in twitter

![image](https://github.com/manifoldmarkets/manifold/assets/18368938/302beb53-d464-4e18-bbaf-c56e0ba29b91)

which market are you seeing this on?
