### ISSUE TITLE
Received notification about me liking my own market

### ISSUE THREAD

**Issue by psirotkin** [manifoldmarkets/manifold#2372]
I received a notification saying user PS liked my market. That would be me; I did not like my market (since that's impossible), and I'm not among the users shown to have liked the market on its page (https://manifold.markets/PS/will-there-be-peace-talks-between-r-c90b2c513101).

![image](https://github.com/manifoldmarkets/manifold/assets/7747812/23ae8bfe-40b1-4b4b-ba46-06fca13e6818)

**Comment by sipec** [comment]
you can no longer like your own market
