### ISSUE TITLE
Limit order notification always show M$0

### ISSUE THREAD

**Issue by Calvin-LL** [manifoldmarkets/manifold#2390]
I keep seeing notifications like these from this market: https://manifold.markets/Stralor/who-will-be-the-republican-nominee-8a36dedc6445

It should not say "M$0"

![Screenshot 2024-01-19 at 12 29 11](https://github.com/manifoldmarkets/manifold/assets/8357970/e29c41bb-9163-46fa-9ef5-781c612d7f60)

I think it's from this component:
 https://github.com/manifoldmarkets/manifold/blob/7feb7be024cc7133fd4a5b1ed13f4771ace9d24c/web/components/notifications/notification-types.tsx#L477

**Comment by sipec** [comment]
resolved by c1521ca6fe2ecf51819ed554b8526ae7c72799b1
