### ISSUE TITLE
NEXT_PUBLIC_FIREBASE_ENV not found

### ISSUE THREAD

**Issue by TrueMilli** [manifoldmarkets/manifold#303]
I've followed the instructions in [Getting Started](https://github.com/manifoldmarkets/manifold#getting-started) and got the following error in Step 3: $ yarn dev:dev

```
yarn run v1.22.18
$ yarn devdev
$ NEXT_PUBLIC_FIREBASE_ENV=DEV concurrently -n NEXT,TS -c magenta,cyan "FIREBASE_ENV=DEV next dev -p 3000" "FIREBASE_ENV=DEV yarn ts --watch" # see https://github.com/vercel/next.js/discussions/33634
Der Befehl "NEXT_PUBLIC_FIREBASE_ENV" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Translation of the German message:
The command "NEXT_PUBLIC_FIREBASE_ENV" is either misspelled or could not be found.

$ yarn dev works.

Let me know if I can provide more information.

**Comment by akrolsmir** [comment]
I think it's probably because you're running this on Windows? We should fix our script to work on Windows as well...

**Comment by TrueMilli** [comment]
Yep, running windows.

**Comment by akrolsmir** [comment]
Should be fixed now that cross-env is used for the script!
