### ISSUE TITLE
Clicking the Home button does not go home

### ISSUE THREAD

**Issue by ahalekelly** [manifoldmarkets/manifold#516]
When on a market page, clicking the home button or the Manifold logo makes the URL change, but the page does not change. If I then leave the page for more than ~15s and return, it will reload the page and go home. Identical on both Firefox and Chrome, but only when I'm logged in. Other buttons in the sidebar work, as well as the home button when I'm on my profile or notifications page.

**Comment by jahooma** [comment]
Thanks for reporting! Just figured out and pushed a fix :-)
