### ISSUE TITLE
Feature request: Cumulative portfolio returns chart

### ISSUE THREAD

**Issue by bcongdon** [manifoldmarkets/manifold#532]
Currently, the user bet's page lists portfolio value and total profits. It'd be nice to have a timeseries chart to see returns over time.

Perhaps something similar to what Kalshi has:
<img width="1053" alt="Screen Shot 2022-06-17 at 7 30 05 AM" src="https://user-images.githubusercontent.com/706257/174318795-d43ba330-d62f-445b-bde8-8907e9899396.png">

**Comment by akrolsmir** [comment]
@Pico2x is working on this! https://github.com/Pico2x/manifold/pull/1
