### ISSUE TITLE
Feature Request: Don't allow people to create duplicate answers in free response questions

### ISSUE THREAD

**Issue by ahalekelly** [manifoldmarkets/manifold#533]
Duplicate answers create a lot of headache, basically every market has to state "in case of duplicates i will resolve to whoever was first"
This change wouldn't stop people from duplicating with a slight change, but it would help

**Comment by akrolsmir** [comment]
Yeah, this ought to be fairly trivial (could just be a client-side fix). Would be a good first-issue!
