### ISSUE TITLE
Feature Request: Sort markets by pool size

### ISSUE THREAD

**Issue by ahalekelly** [manifoldmarkets/manifold#535]

**Comment by wasabipesto** [comment]
I think this is a great suggestion, and should pretty pretty simple a la https://github.com/manifoldmarkets/manifold/commit/688ebb797a9964fb6523f0ea2a1eaa90dfb9d860

Unfortunately I can't get it to work on my build, I think there are some firestore changes that may need to be added as part of this.

**Comment by ahalekelly** [comment]
Sorry what I meant was sort by the size of the betting pool, not the size of the liquidity pool. ie how much money goes to the winners. Could be called Most Invested or something. Since selling has a negative amount, I think you can just sum the amount of all the bets. Compared to Most Traded which is the sum of the absolute value of all the bets.

Sort by liquidity pool would be cool too though. Except free response markets don't have a liquidity pool?

**Comment by ahalekelly** [comment]
oh pool is an object not a number, so it makes sense you can't just sort by it
https://github.com/manifoldmarkets/manifold/blob/dca957708c03430948d20d67b2de321a390d591b/common/contract.ts#L65

**Comment by sipec** [comment]
added and removed (because with limit orders, pool size is no longer a good measure of liquidity)
