### ISSUE TITLE
Fee preview always shows M$0

### ISSUE THREAD

**Issue by ahalekelly** [manifoldmarkets/manifold#536]

**Comment by wasabipesto** [comment]
Can you provide more information on this?

**Comment by ahalekelly** [comment]
It seems to be working again? I was referring to the i in a circle that tells you the fees when you hover over it.
![image](https://user-images.githubusercontent.com/7078138/174507649-692ae67d-7820-4fee-ba38-41c65856f616.png)

**Comment by akrolsmir** [comment]
Hm, closing since it seems to be fixed. Thanks for reporting!
