### ISSUE TITLE
[FR] Manalink improvements

### ISSUE THREAD

**Issue by akrolsmir** [manifoldmarkets/manifold#595]
**Create tab**
- [ ] Narrow the width of the preview, to match the claim page
- [ ] Expires At => Expires in dropdown that has "1 day / 1 week / never" options ala Discord 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/856034/175076653-235d7eaa-aaf9-4689-abe6-47e9744c525f.png">

- [ ] Maybe also the same for max uses? less sure 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/856034/175076727-67807f13-ed0b-4f15-a246-118e45acf50a.png">

**Links tab**
- [ ] Copy text tweaks: "Claimant" to "Claimed by", "Outstanding links" to "Unclaimed links"
- [ ] Created but claimed links should be visible somewhere (eg a new "Claimed links" tab)
- [ ] The green highlight is a bit visually intense, I would try decreasing the color to a lighter green; or use a "new" badge instead eg `new-contract-badge.tsx`
- [ ] There should be a one-click way to copy the generated URL to keyboard, maybe reusing the same component as the market share (though perhaps abbreviated, aka smaller text size and with just the icon, no "Copy Link" text)
<img width="697" alt="image" src="https://user-images.githubusercontent.com/856034/175080510-3584c7ce-913f-4f1f-aa7a-d9f067598fb8.png">

**Claim page**
- [ ] If there's a message included, also display who the sender is on the claim page. Maybe include their avatar on the bottom right before the message eg "😄 Austin: for fixing our graphs"
- [ ] Fully claimed links should be more obviously not claimable - disable/hide claim button; change text, make it grayed out, or sth

**Preview Link**
- [ ]  Instead of the generic preview, should ideally say something like

<img width="536" alt="image" src="https://user-images.githubusercontent.com/856034/176491249-2c8ebedc-92e1-4014-9e87-d2ffd557329f.png">

"Claim M$500 from Austin" (generic)
"M$500, For Rachael & Sinclair Coffee" (with message)

Description: 

"Manifold Markets lets you bet on anything. Predict what will happen in politics, internet culture, Covid, etc. - or start your own market!"

(could tweak description copy to lean into what M$ is too)

**Comment by LivInTheLookingGlass** [comment]
Could you add a way to accept with a delay?
