### ISSUE TITLE
[FR] Add ability to tip markets and free response answers

### ISSUE THREAD

**Issue by bcongdon** [manifoldmarkets/manifold#602]
In addition to comments, it'd be nice if you could tip markets (e.g. for creating an interesting market) and free response answers (e.g. for creating a good or humorous answer)

**Comment by sipec** [comment]
https://github.com/manifoldmarkets/manifold/pull/798 kiinda addresses this
I do want to add market tips for real at some point

**Comment by sipec** [comment]
market tips are in!
