### ISSUE TITLE
API key generation fails silently on browsers that don't support Crypto.randomUUID

### ISSUE THREAD

**Issue by jackkinsey** [manifoldmarkets/manifold#723]
I use qutebrowser (v2.5.2), which is still using QtWebEngine 5.15.10 (based on Chromium 87.0.4280.144). The API key refresh button doesn't render correctly, and nothing happens when I click it; a quick look at the dev console shows that the problem is (at least) that Crypto.randomUUID support is only in Chrome 92 https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID. 

Not even sure this is worth resolving any particular way (maybe just a popup error message for the user telling them to upgrade their browser?), but figured I'd log the issue.

**Comment by sipec** [comment]
closing because browser support of `Crypto.randomUUID` is [quite high](https://caniuse.com/mdn-api_crypto_randomuuid)

Also this specific issue is pretty minor
