### ISSUE TITLE
[Bug] link preview misses the percent sign when writing facebook post

### ISSUE THREAD

**Issue by sipec** [manifoldmarkets/manifold#732]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/18368938/183705375-97c045c2-3706-4a73-b3e7-dc51c59fcd64.png">

Fortunately, the preview looks correct in the actual post. But I worry it might not on similarly small viewports (like phones).

<img width="723" alt="image" src="https://user-images.githubusercontent.com/18368938/183705708-cd720ac0-3ec7-4a2d-a412-06841ec6ec75.png">

**Comment by MaxGhenis** [comment]
Does this still occur for you? I can't reproduce it.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/6076111/203708339-6bfff4d9-1c4b-4e2d-b6b3-4d8654a61f0d.png">
