### ISSUE TITLE
Wysiwyg comment editor is rage-face-emoji

### ISSUE THREAD

**Issue by dreeves** [manifoldmarkets/manifold#795]
## Replicata

1. type the following: 
> `This is a test in which I italicize *this* word and then I go back and make the word "test" also be in italics.`
2. Arrow back to the beginning of the sentence (like the sentence itself explains) and try to put asterisks around a word.

## Expectata

That I end up with "test" and "this" both italicized.

## Resultata

The editor literally ignores me when I try to type the second asterisk around the word "test". 
(In other cases I've seen it italicize a whole paragraph or something and the only workaround is to copy and repaste the whole thing as plain text, losing any italics I'd had so far.

Anti-Magic Principle strikes again!

**Comment by jahooma** [comment]
Thanks for submitting an issue for this! This is definitely something we can work on and improve.

Adding an italics button (and bold and link buttons) to the toolbar would help. But it does seem like there's another issue as well.

**Comment by jahooma** [comment]
🎉
