### ISSUE TITLE
Feature Request: Support commenting via the API

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [manifoldmarkets/manifold#821]
This is currently gating my issue https://github.com/gappleto97/ManifoldMarketManager/issues/5, so if I could comment via the API, my bot could reliably post explanations of why something is being resolved the way it is

**Comment by akrolsmir** [comment]
Hey @gappleto97 -- this is a feature I'd really like as well! I think having an API to allow commenting on any market should be  pretty straightforward, though supporting it as a reply to an existing message might be a bit trickier (but still worth investigating.)

**Comment by LivInTheLookingGlass** [comment]
Oh man, thank you!

**Comment by LivInTheLookingGlass** [comment]
I'm guessing from the 401 errors that it's not deployed for public consumption yet? Doesn't seem to matter which user I run it as

**Comment by LivInTheLookingGlass** [comment]
And deployed
